
name: build

on:
  push:
      paths-ignore:
        - '**/*.md'
        - '.gitignore'
        - '.dependabot/**'
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: brpaz/hadolint-action@master
        with:
          ignore: DL3059 DL3018

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: test
        run: |
          pip install --upgrade pip pipenv
          pip install -r requirements-test.txt
          pytest -v
          docker run -d --name=image-under-test --health-cmd="curl --fail http://127.0.0.1:8200 || exit 1" --health-interval=5s --health-retries=3 image-under-test
          sleep 10
          if [[ -z 'docker ps --filter="name=image-under-test" --filter="health=healthy" -q' ]]; then exit 1; fi

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2

      - name: variables
        run: docker run alpine ash -c "apk update > /dev/null && apk search minidlna" | tail -n +1 | head -n 1 | sed 's/minidlna-//' > version

      - name: build dependencies
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          version: latest

      - name: docker hub login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: build
        run: |
          docker buildx build \
            --push \
            --tag robertbeal/minidlna:latest \
            --tag robertbeal/minidlna:$(cat version) \
            --build-arg=VERSION="$(cat version)" \
            --build-arg=COMMIT_ID="$GITHUB_SHA" \
            --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8 .

